name: Deploy Portfolio (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS PROD
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

            set -e
            cd /www/wwwroot/dwi-purnomo.my.id

            echo "=== DEPLOY START ==="

            git checkout main
            git pull origin main

            echo "Current commit:"
            git log --oneline -1

            # Install dependency TANPA scripts
            composer install \
              --no-interaction \
              --prefer-dist \
              --optimize-autoloader \
              --no-scripts

            # Artisan SELALU sebagai www
            sudo -u www /www/server/php/83/bin/php artisan package:discover
            sudo -u www /www/server/php/83/bin/php artisan migrate --force
            sudo -u www /www/server/php/83/bin/php artisan optimize:clear

            sudo systemctl reload nginx

            echo "=== DEPLOY DONE ==="
          EOF
