name: Test SSH Connection

on:
  workflow_dispatch: # manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY_DEV }}

      - name: Test SSH login
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USER_DEV }}@${{ secrets.VPS_HOST_DEV }} \
          "whoami && pwd && hostname"
